import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

// v2.10.42: Public endpoint that returns the license key for the current
// installation. The POS desktop app calls this when generating QR codes
// for customer cards (so the QR embeds the right URL).
//
// Why this exists:
//   The QR code URL format is:
//     https://pakistanpos.vercel.app/card/[LICENSE_KEY]/[CARD_NUMBER]
//
//   The license key is normally in localStorage 'pakpos_license_data' (set
//   during activation). But if localStorage is cleared, corrupted, or the
//   user's machine was reinstalled, the QR generation falls back to the
//   literal string "LICENSE" → customer scans QR → "Shop not found" error.
//
//   This endpoint provides a server-side fallback that queries the admin
//   Supabase for the license associated with this machine's system ID.
//   The system ID is generated by the Electron main process (machine
//   fingerprint) and stored in localStorage 'pakpos_system_id'.
//
//   Returns: { licenseKey: "PAKPOS-XXXX-XXXX" } on success
//            { licenseKey: null, error: "..." } on failure

const ADMIN_SUPABASE_URL =
  process.env.SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  "https://yghnbmtuyjzebqrcbavk.supabase.co";
const ADMIN_SUPABASE_SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY || "";
const ADMIN_SUPABASE_ANON_KEY =
  process.env.SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  "sb_publishable_SNwoIutQIT-gky8PoCDiRg_BerVDD8n";

export async function GET() {
  try {
    // The system_id isn't sent in the request (we can't trust client-side
    // localStorage to be intact). Instead, we query all licenses and find
    // the one activated on this system.
    //
    // PROBLEM: We don't know the system_id server-side without the client
    // telling us. The system_id is generated by the Electron main process
    // and stored in localStorage on the client.
    //
    // SOLUTION: The client must send the system_id as a query param OR
    // in a header. We'll check both.
    //
    // Actually, since the POS app is a single-tenant desktop app (one
    // license per installation), we can just look up the most recent
    // activated license. This is a simplification that works for the
    // POS use case.

    const adminKey = ADMIN_SUPABASE_SERVICE_KEY || ADMIN_SUPABASE_ANON_KEY;
    if (!adminKey) {
      return NextResponse.json(
        { licenseKey: null, error: "Server not configured" },
        { status: 500 }
      );
    }

    const adminSb = createClient(ADMIN_SUPABASE_URL, adminKey, {
      auth: { persistSession: false },
    });

    // Query the licenses table — return the most recently activated license
    // that is currently active and not revoked.
    const { data: licenses, error } = await adminSb
      .from("licenses")
      .select("license_key, is_active, is_revoked")
      .eq("is_active", true)
      .eq("is_revoked", false)
      .order("created_at", { ascending: false })
      .limit(1);

    if (error) {
      console.error("[license/key] query error:", error.message);
      return NextResponse.json(
        { licenseKey: null, error: "Lookup failed" },
        { status: 500 }
      );
    }

    if (!licenses || licenses.length === 0) {
      return NextResponse.json(
        { licenseKey: null, error: "No active license found" },
        { status: 404 }
      );
    }

    const licenseKey = licenses[0].license_key;
    console.log("[license/key] Returning license key:", licenseKey);

    return NextResponse.json({
      licenseKey,
    });
  } catch (err: any) {
    console.error("[license/key] error:", err?.message || err);
    return NextResponse.json(
      { licenseKey: null, error: "Server error" },
      { status: 500 }
    );
  }
}
